fix indentation in devcontainer workflow

diff --git a/.github/workflows/devcontainer.yml b/.github/workflows/devcontainer.yml
--- a/.github/workflows/devcontainer.yml
+++ b/.github/workflows/devcontainer.yml
@@ -15,7 +15,7 @@ jobs:
   build:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
+      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
       - run: docker build .devcontainer
 
   rust-version:
@@ -23,11 +23,10 @@ jobs:
     steps:
       - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579
       - run: |
-        expected=$(cat rust-toolchain)
-        versions=$(sed -nE 's|^FROM (.*/)?rust:([^ -]+)|\2|p' .devcontainer/Dockerfile)
-        ex=0
-        for mismatch in $(echo "$versions" | grep -F "$(cat rust-toolchain)" || true)
-          echo "::error file=.devcontainer/Dockerfile::Devcontainer uses incorrect rust version(s): $mismatch"
-          ex=$((ex + 1))
-        fi
-        exit $ex
+          versions=$(sed -nE 's|^FROM (.*/)?rust:([^ -]+)|\2|p' .devcontainer/Dockerfile)
+          ex=0
+          for mismatch in $(echo "$versions" | grep -F "$(cat rust-toolchain)" || true)
+            echo "::error file=.devcontainer/Dockerfile::Devcontainer uses incorrect rust version(s): $mismatch"
+            ex=$((ex + 1))
+          fi
+          exit $ex
