???

diff --git a/.github/workflows/toolchain.yml b/.github/workflows/toolchain.yml
--- a/.github/workflows/toolchain.yml
+++ b/.github/workflows/toolchain.yml
@@ -19,11 +19,17 @@ jobs:
       - uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3
       - run: git config --global --add safe.directory "$PWD" # actions/runner#2033
       - run: |
-          VERSION="$(grep 'channel = ".*"' rust-toolchain.toml | grep '[0-9]+.[0-9]+.[0-9]+' --only-matching)"
-          if [ "$(cargo --version | cut -d' ' -f2)" != "$VERSION" ]; then
-            echo "::error file=rust-toolchain::rust-toolchain $VERSION does not match devcontainer $(cargo --version)"
+          VERSION_REGEX='channel = "[0-9]+.[0-9]+.[0-9]+"'
+          if [[ "$(cat rust-toolchain.toml)" ~= "$VERSION_REGEX" ]]; then
+            if [ "$(cargo --version | cut -d' ' -f2)" != "$VERSION" ]; then
+              echo "::error file=rust-toolchain.toml::rust-toolchain $VERSION does not match devcontainer $(cargo --version)"
+              exit 1
+            fi
+          else
+            echo "::error file=rust-toolchain.toml::failed to parse rust-toolchain.toml"
             exit 1
           fi
+
 
   workflows:
     runs-on: ubuntu-latest
